# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20170925_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verescutarescrever',
            name='author',
        ),
        migrations.DeleteModel(
            name='VerEscutarEscrever',
        ),
    ]
